<?php

namespace Tests;

use App\Models\Account;
use App\Models\AccountType;
use Database\Seeders\AccountTypeSeeder;
use Database\Seeders\DefaultSettingSeeder;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
		$this->seed([AccountTypeSeeder::class, DefaultSettingSeeder::class]);

	}

	protected function makeTcAccount(): array
	{
		$tcAccountType = AccountType::find(1);

		$defaultSetting = $tcAccountType->defaultSettings;

		return [
			$defaultSetting,
			Account::factory()->create([
				'account_type_id' => $tcAccountType->id
			])
		];
	}
}
