<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    use HasFactory;

	protected static function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub

		static::created(function ($model) {
			$model->settings()->create([
				'settings_default_id' => 1,
				'account_id' => $model->id,
				'value' => 1
			]);
		});
	}

	public function accountType()
	{
		return $this->belongsTo(AccountType::class);
	}

	public function users()
	{
		return $this->hasMany(User::class);
	}

	public function settings()
	{
		return $this->hasMany(Setting::class);
	}
}
